name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --no-save

      - name: Configure Git
        run: |
          git config --global user.email "hi@emilgram.dk"
          git config --global user.name "EmilGramDK"

      - name: Bump version
        run: bun pm version patch --message "Bump version to %s" --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Format Code
        run: bun run format

      - name: Lint Code
        run: bun run lint

      - name: Publish to npm
        run: bun publish
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push version update
        run: git push --follow-tags
